plugins {
    id "com.android.application"
}

android {
    namespace "com.browseruse.workout"
    compileSdk 35
    buildToolsVersion "35.0.0"

    defaultConfig {
        applicationId "com.browseruse.workout.v159"
        minSdk 23
        targetSdk 35
        versionCode 62
        versionName "15.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"
        }
    }
}
